name: Reusable workflow

on:

  workflow_call:

    inputs:
    
      author:
        required: true
        type: string

      should:
        required: true
        type: boolean

jobs:

  reuse:

    if: inputs.should

    runs-on: ubuntu-latest

    steps:
      - run: echo ${{ inputs.author }}
