on:

  push:
    branches: [main]

jobs:

  dotenv_outputs:

    name: Load dotenv output variables
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.env.outputs.version }}
      author: ${{ steps.env.outputs.author }}

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Use dotenv for output variables
        id: env
        uses: falti/dotenv-action@v0.2.7
        with:
          log-variables: true


  script_outputs:

    name: Load script output variables
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.script.outputs.version }}
      author: ${{ steps.script.outputs.author }}

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Use script for output variables
        id: script
        run: .github/workflows/set_output_variables


  call_workflow_with_dotenv_outputs:

    needs: dotenv_outputs

    name: Call reusable workflow with dotenv output variables

    uses: staticaland/dumb-reusable-actions/.github/workflows/reusable-workflow.yml@main

    with:
      author: ${{ needs.dotenv.outputs.author }}


  call_workflow_with_script_outputs:

    needs: script_outputs

    name: Call reusable workflow with script output variables

    uses: staticaland/dumb-reusable-actions/.github/workflows/reusable-workflow.yml@main

    with:
      author: ${{ needs.script_outputs.outputs.author }}