on:

  push:
    branches: [main]

jobs:

  dotenv:

    name: Dotenv
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.env.outputs.version }}
      author: ${{ steps.env.outputs.author }}

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Dotenv Action
        id: env
        uses: falti/dotenv-action@v0.2.7
        with:
          log-variables: true


  call-workflow-with-dotenv:
    needs: dotenv
    uses: staticaland/dumb-reusable-actions/.github/workflows/reusable-workflow.yml@main
    with:
      author: ${{ needs.dotenv.outputs.author }}