on:

  push:
    branches: [main]

jobs:

  dotenv_outputs:

    name: Load dotenv output variables
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.env.outputs.version }}
      author: ${{ steps.env.outputs.author }}

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Use dotenv for output variables
        id: env
        uses: falti/dotenv-action@v0.2.7
        with:
          log-variables: true


  python_outputs:

    name: Load Python output variables
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.python.outputs.version }}
      author: ${{ steps.python.outputs.author }}

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Python for output variables
        id: python
        run: python .github/workflows/set_output_variables.py


  script_outputs:

    name: Load script output variables
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.script.outputs.version }}
      author: ${{ steps.script.outputs.author }}

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Use script for output variables
        id: script
        run: .github/workflows/set_output_variables


  action_script_outputs:

    name: Load Action script output variables
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.action_script.outputs.version }}
      author: ${{ steps.action_script.outputs.author }}

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Action script for output variables
        id: action_script
        uses: actions/github-script@v3
        with:
          script: |
            core.setOutput('version', "1.0")
            core.setOutput('author', "Mickey Mouse")


  static_outputs:

    name: Load static output variables
    runs-on: ubuntu-latest

    outputs:
      version: "1.0"
      author: "Mickey Mouse"

    steps:
      - name: Use static output variables
        id: script
        run: true


  call_workflow_with_dotenv_outputs:

    needs: dotenv_outputs

    name: Call reusable workflow with dotenv output variables

    uses: staticaland/dumb-reusable-actions/.github/workflows/reusable-workflow.yml@main

    with:
      author: ${{ needs.dotenv_outputs.outputs.author }}


  call_workflow_with_script_outputs:

    needs: script_outputs

    name: Call reusable workflow with script output variables

    uses: staticaland/dumb-reusable-actions/.github/workflows/reusable-workflow.yml@main

    with:
      author: ${{ needs.script_outputs.outputs.author }}


  call_workflow_with_action_script_outputs:

    needs: action_script_outputs

    name: Call reusable workflow with Action script output variables

    uses: staticaland/dumb-reusable-actions/.github/workflows/reusable-workflow.yml@main

    with:
      author: ${{ needs.action_script_outputs.outputs.author }}


  call_workflow_with_python_outputs:

    needs: python_outputs

    name: Call reusable workflow with Python output variables

    uses: staticaland/dumb-reusable-actions/.github/workflows/reusable-workflow.yml@main

    with:
      author: ${{ needs.python_outputs.outputs.author }}

  
  call_workflow_with_static_outputs:

    needs: static_outputs

    name: Call reusable workflow with static output variables

    uses: staticaland/dumb-reusable-actions/.github/workflows/reusable-workflow.yml@main

    with:
      author: ${{ needs.static_outputs.outputs.author }}