on:

  push:
    branches: [main]

jobs:

  dotenv:

    name: Load dotenv variables
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.env.outputs.version }}
      author: ${{ steps.env.outputs.author }}

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Dotenv Action
        id: env
        uses: falti/dotenv-action@v0.2.7
        with:
          log-variables: true

  call-workflow-with-dotenv:

    needs: dotenv

    name: Call reusable workflow with dotenv variables

    uses: staticaland/dumb-reusable-actions/.github/workflows/reusable-workflow.yml@main

    with:
      author: ${{ needs.dotenv.outputs.author }}