on:

  push:
    branches: [main]

jobs:

  dotenv:

    name: Dotenv
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.env.outputs.version }}
      author: ${{ steps.env.outputs.author }}

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Dotenv Action
        id: env
        uses: falti/dotenv-action@v0.2.7
        with:
          log-variables: true

  dumb:

    runs-on: ubuntu-latest
    needs: dotenv

    steps:
      - name: Try
        run: echo ${{ needs.dotenv.outputs.version }} ${{ needs.dotenv.outputs.author }}
        